language: cpp
compiler: gcc
dist: trusty
notifications:
  email: false

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - pip install --user cpp-coveralls

  
install: 
  # C++17
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90
   
  # install newer LCOV (apt version outdated and fails for new gcov).
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install  
  - which lcov 

before_script:
  - g++ --version
  - PARENTDIR=$(pwd)

script:
  - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Coverage
  - cd build
  - cmake --build .
  - ctest -VV


after_success:
- coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"
